# -*- coding: utf-8 -*-
"""iris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tA5wVCjOlxUwPiukijETMubFBlVBNyhj
"""

import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
import joblib

# Load Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

# Train Logistic Regression model
model = LogisticRegression(max_iter=200)
model.fit(X, y)

# Save the trained model
joblib.dump(model, 'iris_logistic_regression_model.pkl')

# Encode labels and save encoder
encoder = LabelEncoder()
encoder.fit(y)
joblib.dump(encoder, 'iris_encoder.pkl')

print("Model and encoder saved!")

